// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Contexts;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230528182110_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f0237b71-fe5d-40b5-af1a-f703e065998d",
                            ConcurrencyStamp = "bfc0e556-1074-4579-a3be-2403a602bcbd",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "12fddf82-afca-405b-9c7a-f827156eb4b1",
                            ConcurrencyStamp = "99a86d6d-e357-496b-8fbb-295190f39f4c",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Entities.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WebApp.Models.Entities.ContactFormEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactForms");
                });

            modelBuilder.Entity("WebApp.Models.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "HyperX Cloud II Gaming Headset i rött och svart har en avancerad USB audio control box med inbyggt DSP ljudkort, detta stärker ljud och tal så att du får en optimal gaming upplevelse. Med virtual 7.1 surround sound i kombination med stängda kåpor upplever du en detaljrikedom du tidigare aldrig hört! Mikrofon och ljud har separata volymkontroller som gör det lätt att höja och sänka volymen oberoende av varandra. Kompatibelt med PC & Mac via USB och stereokompatibelt med PS4, Xbox One1 och mobil. ",
                            ImageUrl = "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_80726870/fee_786_587_png/HYPERX-Cloud-II-Wireless---Tr%C3%A5dl%C3%B6st-Gamingheadset-f%C3%B6r-PC--PS4-%26-Nintendo-Switch",
                            Price = 119m,
                            Title = "HyperX Cloud 2"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Den här formen kommer från vår prisbelönta DeathAdder-ergonomi och är utformad för små till medelstora handstorlekar och är mångsidig nog för att passa de flesta greppstilar. Till nollkostnad för att bygga hållfasthet har chassit också kastat bort mer vikt så att du kan dra av enkla svepningar och spela under långa timmar i komfort.\r\n\r\nMed förbättrad taktilitet för skarpare och mer tillfredsställande klick aktiverar omkopplarna i denna lilla ergonomiska spelmus med en branschledande responstid på 0,2 millisekunder. Genom att använda en infraröd ljusstråle istället för fysisk kontakt för att registrera varje klick, tar denna form av aktivering bort behovet av avstängningsfördröjning och utlöser aldrig oavsiktliga klick, vilket ger dig närmare kontroll och felfri utförande. ",
                            ImageUrl = "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSYnJyGs3FmYgpXDPlRqMFwRU86cUlY6PCE0gedPYcUeCnvTXYFoZfPOxoIVlGCTgifbnT72rKoctXdXEhKRWDyGrpWn8P2y2xxfBotAEOU0jeeCf0qRzmHSSCUfXd1aH9_VUva&usqp=CAc",
                            Price = 123m,
                            Title = "Razer Deathadder"
                        },
                        new
                        {
                            Id = 3,
                            Description = "MSI GF63 Thin bärbar dator för gaming är byggd med både hållbarhet och prestanda i åtanke. Tack vare metallchassit och det långvariga batteriet kan du ta ditt spelande på språng utan att behöva oroa dig",
                            ImageUrl = "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRqyp5LozRGVoVB47jxuVY0FQV4d55gzmijVDef8TPGFWWBEODjL1aqADg-r_vUDj5hLM83XgRq44jVIIvpcrma44d_FE7IAcyyDR6BK1pfx7-GF2TBqoQ&usqp=CAc",
                            Price = 1200m,
                            Title = "MSI GF63"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Varje detalj i GMMK 2 Pre-built från Glorius har noggrant utformats för att ge dig den ultimata skriv- och spelupplevelsen. Den anodiserade aluminiumramen ger en solid grund för de inkluderade double-shot keycapsen, som använder ett rent typsnitt som aldrig bleknar. Hotswap-stöd gör att användarna enkelt kan koppla in sin önskade switchar. Glorious linjära Fox-switchar och stabilisatorer är pre-lubed för att vara mjuka, och det tjocka interna skummaterialet säkerställer en förstklassig ljudkvalitet. ",
                            ImageUrl = "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRn6vt-ynbab_gYnu59ovKYcf9m26C-fS3oMoDv4YvYWWnNluIBJFdKZe3WKa2WsUsVv57hpVBULm9Qcr4ouhoEIlIeyNeDLqyZJ9zwftuSI8JlAHVl4v68TcycE5WRbBzpnw&usqp=CAc",
                            Price = 79m,
                            Title = "Glorious GMMK 2"
                        },
                        new
                        {
                            Id = 5,
                            Description = "G2412 från MSI är en bildskärm perfekt för gaming. G2412 gamingskärm har 23.8” och levererar hela 170 bilder per sekund med sin FreeSync Premium teknologi med en otroligt snabb responstid på endast 1ms. Bildskärmen har 16.7 miljoner färger, 1100:1 i kontrast och ett brett bildförhållande på 16:9 med en justerbar lutning på -5° ~ 20°.",
                            ImageUrl = "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRhk2LD0zCMVYuQh7Tn4ScDBHkaTG8z4iRdps16e41PWFTRi2QxGRnlhPKiWB3POnhG1HogyH0kEj0zQ4LmglNMzkt1wzyAkyABkFuDDJrp7EusG14v04W7Mr33AuLrneJBeQ&usqp=CAc",
                            Price = 135m,
                            Title = "MSI G2412"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Model O är en solid mus som har egenskaper de flesta tillverkare bara drömmer om att få använda när de tillverkar gamingmöss. Nu tar dom steget upp till nästa nivå med en av de mest avancerade sensorer som någonsin konstruerats, deras egna BAMF-sensor. Model-O Wireless utnyttjar kraften i BAMF sensoren och det isiga, släta glidet från deras G-skates för att ge dig maximal kontroll, minimalt med friktion och noll fördröjning.",
                            ImageUrl = "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTwCW8aB33v_fsuHcPMsk999ZuffyecrPaOqKrCC5tEO4SUHXDPzg5B0YkdoMP3xkgfsXle90CJ27tBs_I1de6EqM8K9nZVQQ-JNMys5IRBkmISVTfwn_AF5fDi2Z51_6aqSNg&usqp=CAc",
                            Price = 59m,
                            Title = "Glorious Model O"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Hör och låt som ett proffs med Logitech PRO X. Med Blue VOICE-mikrofonteknik och nästa generations 7.1-surroundljud. Det externa USB-ljudkortet ger dig högkvalitativ kristallklart ljud. Designat för turneringar med nedladdningsbara ljud EQ. ",
                            ImageUrl = "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSSA1T7g6EGImiCBiOhngW2vye9UiKz1otq2vZfPweJcytckNt2y67r9L5wxrsYDc79dOk92zcIEJXh7fy9EHku4oBlZ-DeLPYn1sRh7ewh6C8GFNQzOQ1xKcrXoBQNJy9G8A&usqp=CAc",
                            Price = 44m,
                            Title = "Logitech G PRO X"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Byggt för proffsen, inifrån och ut. Med sin kompakta design utan numerisk knappsats frigör det mekaniska speltangentbordet Logitech G® PRO bordsyta för lågkänsliga musrörelser. Clicky-brytare i proffsklass ger hörbar återkoppling. Med programmerbar LIGHTSYNC RGB och inbyggt minne kan du lagra anpassade belysningsmönster för turneringar.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR-Ia36fWUj3UynzprsqdYtaEyKvN6N6ABt3bt4z5_nXXr6lFIGWnhRQkIKLrjjRG-WTizzqnR_TdmhgOpK-q7nuMFSlbCbD6toYEEzPGPdtPb5mLEUe8jiQg&usqp=CAc",
                            Price = 62m,
                            Title = "Logitech G PRO "
                        },
                        new
                        {
                            Id = 9,
                            Description = "Extra bred musmatta med högkvalitativ ultravävd yta som har utmärkt glidförmåga, sydda kanter och halkskyddad undersida.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSzFXVTBEfegK4S687W39k16CHUJRCC-IeYLPAGquVEiMTjhJHgltLVsf3lhBRrRpS9Pb2xdrGtiXRTyHg83Ye7GxfamA9dqnHsonkyNqCnWcZTiZiZknLmG0Me-FtYso0Ftw&usqp=CAc",
                            Price = 13m,
                            Title = "Steelseries QcK"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Entities.ProductTagEntity", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 9,
                            TagId = 3
                        });
                });

            modelBuilder.Entity("WebApp.Models.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TagName = "new"
                        },
                        new
                        {
                            Id = 2,
                            TagName = "featured"
                        },
                        new
                        {
                            Id = 3,
                            TagName = "popular"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Entities.UserAddressEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("WebApp.Models.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebApp.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebApp.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebApp.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Models.Entities.ProductTagEntity", b =>
                {
                    b.HasOne("WebApp.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Entities.TagEntity", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebApp.Models.Entities.UserAddressEntity", b =>
                {
                    b.HasOne("WebApp.Models.Entities.AddressEntity", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Entities.UserEntity", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApp.Models.Entities.AddressEntity", b =>
                {
                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("WebApp.Models.Entities.ProductEntity", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("WebApp.Models.Entities.TagEntity", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("WebApp.Models.Entities.UserEntity", b =>
                {
                    b.Navigation("UserAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
